'use client';
import Link from 'next/link';
const C = { bg: '#0A0A0A', text: '#F5F5F0', textSecondary: '#B8B4AC', primary: '#C8B89A' };
export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: C.bg, color: C.text, padding: '60px 20px' }}>
      <div style={{ maxWidth: '800px', margin: '0 auto' }}>
        <Link href="/" style={{ color: C.primary, textDecoration: 'none', fontSize: '14px', marginBottom: '32px', display: 'inline-block' }}>← Back</Link>
        <h1 style={{ fontSize: '32px', fontWeight: 800, marginBottom: '12px' }}>Terms of Service</h1>
        <p style={{ color: C.textSecondary, marginBottom: '40px' }}>Effective: June 22, 2026</p>
        <div style={{ lineHeight: '1.8', color: C.textSecondary }}>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>1. Introduction & Acceptance</h2>
          <p>Welcome to ValueSkins. These Terms of Service ("Terms") govern your access to and use of the ValueSkins platform, website, mobile applications, and related services (collectively, the "Platform"). The Platform is operated by ValueSkins Technologies Pvt. Ltd. ("Company," "we," "us," or "our").</p>
          <p>By creating an account, accessing, or using the Platform, you agree to be bound by these Terms. If you do not agree to these Terms, you must not access or use the Platform. These Terms constitute a binding legal agreement between you and the Company.</p>
          <p><strong>Electronic Record:</strong> These Terms are an electronic record generated by a computer system and do not require any physical or digital signatures. They are published in accordance with the provisions of the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>2. Definitions</h2>
          <p><strong>"Platform"</strong> means the ValueSkins website, mobile applications, and all related services.</p>
          <p><strong>"User"</strong> means any person who accesses or uses the Platform.</p>
          <p><strong>"Creator"</strong> means a User who creates a profile offering creative or professional services through the Platform.</p>
          <p><strong>"Brand"</strong> means a User who engages Creators for promotional or professional services through the Platform.</p>
          <p><strong>"Deal"</strong> means a binding agreement between a Creator and a Brand facilitated through the Platform.</p>
          <p><strong>"Escrow"</strong> means the payment protection mechanism whereby funds are held by Razorpay (our payment processor) and released only upon fulfilment of agreed conditions.</p>
          <p><strong>"Deliverables"</strong> means the work product, content, or services to be provided by a Creator as specified in a Deal.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>3. Eligibility & Account Registration</h2>
          <p><strong>Age Requirement:</strong> You must be at least 18 years of age to use the Platform. If you are between 13 and 18 years of age, you may use the Platform only with the consent and supervision of a parent or legal guardian who agrees to be bound by these Terms.</p>
          <p><strong>Account Registration:</strong> You must create an account to use certain features of the Platform. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.</p>
          <p><strong>Account Security:</strong> You are solely responsible for maintaining the confidentiality of your account credentials, including your password. You are fully responsible for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account or any other breach of security.</p>
          <p><strong>One Account Per User:</strong> You may not create multiple accounts. We reserve the right to merge or disable duplicate accounts.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>4. Platform Services</h2>
          <p>ValueSkins is a marketplace platform that facilitates connections between Creators and Brands. Our services include:</p>
          <p>• Profile creation and discovery tools for Creators and Brands</p>
          <p>• Deal creation, negotiation, and management tools</p>
          <p>• Escrow-based payment processing through Razorpay</p>
          <p>• Messaging and collaboration tools</p>
          <p>• Deliverable submission and review workflows</p>
          <p>• Dispute resolution mechanisms</p>
          <p><strong>Platform Role:</strong> ValueSkins is a platform facilitator and not a party to any agreement between Creators and Brands. We do not employ, endorse, or supervise Creators. We do not control the quality, safety, or legality of services offered. Each Deal created on ValueSkins constitutes a binding agreement between the Creator and Brand under the Indian Contract Act, 1872.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>5. Payment Terms & Escrow</h2>
          <p><strong>Payment Processor:</strong> All payments on the Platform are processed through Razorpay (for INR transactions) and Stripe (for USD transactions). By using the Platform, you agree to be bound by Razorpay's and/or Stripe's terms of service and privacy policies.</p>
          <p><strong>Escrow Arrangement:</strong> When a Brand funds a Deal, the payment is held in escrow by Razorpay. The Company never holds, controls, or has access to the funds. Funds are released from escrow only upon fulfilment of the conditions agreed upon in the Deal.</p>
          <p><strong>Platform Fee:</strong> The Company charges a platform fee of 2% (plus applicable GST) on each completed transaction. The fee is deducted from the payment before release to the Creator.</p>
          <p><strong>Taxes:</strong> Users are solely responsible for all taxes, including but not limited to GST, TDS, and income tax, arising from their use of the Platform and their transactions. The Company does not provide tax advice. Creators earning above applicable thresholds must obtain GST registration and issue invoices to Brands as required by law.</p>
          <p><strong>Payouts:</strong> Upon successful completion of a Deal, funds are released to the Creator's registered payout account (bank account or UPI ID) by Razorpay. Payout timelines are subject to Razorpay's processing schedules and applicable banking regulations.</p>
          <p><strong>Refunds:</strong> Refunds are governed by the Deal terms agreed between the Creator and Brand. In the event of a dispute, refunds will be processed in accordance with our Dispute Resolution process (Section 11).</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>6. Deals & Contracts</h2>
          <p><strong>Deal Creation:</strong> A Deal is created when a Brand submits a brief and the Creator accepts it. The Deal terms include deliverables, timeline, payment amount, revision count, and other agreed conditions.</p>
          <p><strong>Binding Agreement:</strong> Each accepted Deal constitutes a legally binding agreement between the Creator and Brand under the Indian Contract Act, 1872. The Company is not a party to this agreement.</p>
          <p><strong>Deal Lifecycle:</strong> Deals progress through defined stages: Draft → Negotiation → Agreement → Funded → In Progress → Review → Completed/Cancelled/Disputed. Each stage has specific rules governing timelines, approvals, and actions.</p>
          <p><strong>Auto-Resolution:</strong> If a Brand fails to review Deliverables within 7 days, the Deliverables are deemed approved and funds are released. If a Creator fails to submit Deliverables within the agreed timeline, the Brand may cancel the Deal and receive a full refund.</p>
          <p><strong>Cancellation & Kill Fees:</strong> Deals may be cancelled by mutual agreement (full refund) or through the kill fee process (partial payment for partial delivery). If no resolution is reached within 14 days, the escrow is split on a predefined basis (70% to Brand, 30% to Creator) unless either party objects within 48 hours of notice.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>7. Intellectual Property</h2>
          <p><strong>User Content:</strong> You retain all ownership rights to content you submit, post, or display on or through the Platform ("User Content"). By submitting User Content, you grant the Company a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, adapt, publish, and display such User Content solely for the purpose of operating, providing, and improving the Platform.</p>
          <p><strong>Deliverables License:</strong> Unless otherwise agreed in a Deal, Creators grant Brands a non-exclusive, perpetual, worldwide license to use Deliverables for the campaign or purpose described in the Deal. Any use beyond the scope of the Deal requires separate compensation agreed between the Creator and Brand. Creators retain all ownership rights not expressly granted.</p>
          <p><strong>Platform IP:</strong> The Platform, including its design, code, algorithms, trademarks, and branding, is owned by the Company and protected by applicable intellectual property laws. You may not copy, modify, distribute, reverse engineer, or create derivative works of the Platform without our express written consent.</p>
          <p><strong>Feedback:</strong> Any suggestions, ideas, or feedback you provide to us about the Platform may be used by us without compensation or obligation to you.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>8. User Conduct & Prohibited Activities</h2>
          <p>You agree not to engage in any of the following prohibited activities:</p>
          <p>• Violating any applicable law, regulation, or these Terms</p>
          <p>• Impersonating any person or entity or misrepresenting your affiliation</p>
          <p>• Harassing, abusing, threatening, or intimidating other Users</p>
          <p>• Uploading malware, viruses, or any harmful code</p>
          <p>• Attempting to circumvent the Platform's escrow system or conduct deals off-platform</p>
          <p>• Using automated scripts, bots, or scrapers to access the Platform</p>
          <p>• Interfering with the operation of the Platform or its infrastructure</p>
          <p>• Collecting User information without consent</p>
          <p>• Engaging in fraudulent, deceptive, or misleading activities</p>
          <p>• Posting content that is defamatory, obscene, or infringes on third-party rights</p>
          <p><strong>Monitoring:</strong> We reserve the right to monitor User activity and content for compliance with these Terms. We may remove or disable access to any content that violates these Terms.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>9. Communication & Recording</h2>
          <p>All deal-related communications (messages, offers, counter-offers, contract terms, file submissions) sent through the Platform are permanently recorded with tamper-evident storage and server-authoritative timestamps. By sending messages through the Platform, you consent to this recording. A notice of recording is displayed before your first message in any deal room.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>10. Third-Party Services</h2>
          <p>The Platform integrates with third-party services including but not limited to Razorpay, Stripe, Supabase, Google, and GitHub. Your use of these services is subject to their respective terms and policies. We are not responsible for the acts or omissions of third-party service providers.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>11. Dispute Resolution</h2>
          <p><strong>Informal Resolution:</strong> Before initiating any formal proceeding, you agree to contact us at <Link href="mailto:support@valueskins.com" style={{color: C.primary}}>support@valueskins.com</Link> and attempt to resolve the dispute informally for 30 days.</p>
          <p><strong>Platform Dispute Process:</strong> Disputes between Creators and Brands regarding a Deal will first go through the Platform's internal dispute resolution process. The Company may facilitate resolution but does not guarantee a particular outcome.</p>
          <p><strong>Arbitration:</strong> Any dispute arising out of or relating to these Terms or your use of the Platform that cannot be resolved informally shall be resolved by binding arbitration administered in accordance with the Arbitration and Conciliation Act, 1996. The arbitration shall be conducted in English in Mumbai, India, by a sole arbitrator appointed by mutual agreement.</p>
          <p><strong>Class Action Waiver:</strong> You agree to resolve disputes on an individual basis and waive any right to participate in a class action or representative proceeding.</p>
          <p><strong>Governing Law:</strong> These Terms shall be governed by and construed in accordance with the laws of India. The courts of Mumbai, Maharashtra shall have exclusive jurisdiction over any matters not subject to arbitration.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>12. Limitation of Liability & Disclaimer</h2>
          <p><strong>Disclaimer:</strong> THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE COMPANY MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.</p>
          <p><strong>Limitation of Liability:</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE PLATFORM.</p>
          <p><strong>Liability Cap:</strong> THE COMPANY'S TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF (A) THE FEES PAID BY YOU TO THE COMPANY IN THE 12 MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ₹10,000 INDIAN RUPEES. THIS CAP APPLIES WHETHER THE ACTION IS IN CONTRACT, TORT, OR ANY OTHER THEORY.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>13. Indemnification</h2>
          <p>You agree to indemnify, defend, and hold harmless the Company, its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to: (a) your use of the Platform; (b) your violation of these Terms; (c) your User Content; (d) your violation of any rights of a third party; or (e) any Deal you enter into through the Platform.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>14. Account Suspension & Termination</h2>
          <p><strong>By You:</strong> You may delete your account at any time through the Platform settings. Account deletion initiates a 30-day grace period during which you may cancel the deletion request. After 30 days, your data is permanently deleted in accordance with our Privacy Policy.</p>
          <p><strong>By Us:</strong> We reserve the right to suspend or terminate your account at any time, without prior notice, if: (a) you violate these Terms; (b) we suspect fraudulent, abusive, or illegal activity; (c) we are required to do so by law; or (d) your conduct could harm the Company or other Users.</p>
          <p><strong>Effect of Termination:</strong> Upon termination, you lose access to your account and any pending Deals may be cancelled. Outstanding escrow funds will be handled per the Deal terms and applicable law. Sections 7, 11, 12, 13, 15, and 16 of these Terms survive termination.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>15. Changes to Terms</h2>
          <p>We may modify these Terms at any time. We will provide at least 30 days' notice of material changes either by email or through the Platform. Your continued use of the Platform after the changes take effect constitutes your acceptance of the modified Terms. If you do not agree to the modified Terms, you must stop using the Platform.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>16. General Provisions</h2>
          <p><strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and the Company regarding your use of the Platform.</p>
          <p><strong>Severability:</strong> If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>
          <p><strong>Waiver:</strong> The failure to enforce any provision of these Terms shall not constitute a waiver of such provision.</p>
          <p><strong>Assignment:</strong> You may not assign these Terms without our consent. We may assign these Terms without restriction.</p>
          <p><strong>Notices:</strong> Notices to you may be sent via email or through the Platform. Notices to us must be sent to <Link href="mailto:legal@valueskins.com" style={{color: C.primary}}>legal@valueskins.com</Link> or to our registered address.</p>

          <h2 style={{ fontSize: '20px', fontWeight: 700, color: C.text, marginTop: '24px', marginBottom: '12px' }}>17. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at:</p>
          <p><strong>Email:</strong> <a href="mailto:founder@valueskins.com" style={{color: C.primary}}>founder@valueskins.com</a></p>
          <p><strong>Phone:</strong> <a href="tel:+919665820468" style={{color: C.primary}}>+91 96658 20468</a></p>
          <p><strong>Support:</strong> <a href="mailto:support@valueskins.com" style={{color: C.primary}}>support@valueskins.com</a></p>
          <p><strong>Address:</strong> ValueSkins Technologies Pvt. Ltd., Mumbai, Maharashtra, India</p>

        </div>
      </div>
    </div>
  );
}
