/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#000',
        'surface-dim': '#000',
        'surface-lowest': '#000',
        'surface-container-low': '#0a0a0a',
        'surface-container': '#0d0d0d',
        'surface-container-high': '#111',
        'surface-container-highest': '#1a1a1a',
        'surface-bright': '#1a1a1a',
        'surface-variant': '#1a1a1a',
        'on-surface': '#e5e5e5',
        'on-surface-variant': '#a3a3a3',
        'inverse-surface': '#f5f5f5',
        'inverse-on-surface': '#404040',
        'background': '#000',
        'on-background': '#e5e5e5',
        'primary': '#3b82f6',
        'primary-dim': '#2563eb',
        'primary-fixed': '#60a5fa',
        'primary-fixed-dim': '#3b82f6',
        'primary-container': '#1d4ed8',
        'on-primary': '#fff',
        'on-primary-fixed': '#000',
        'on-primary-fixed-variant': '#fff',
        'on-primary-container': '#bfdbfe',
        'inverse-primary': '#3b82f6',
        'secondary': '#a78bfa',
        'secondary-dim': '#8b5cf6',
        'secondary-fixed': '#c4b5fd',
        'secondary-fixed-dim': '#a78bfa',
        'secondary-container': '#5b21b6',
        'on-secondary': '#fff',
        'on-secondary-fixed': '#fff',
        'on-secondary-fixed-variant': '#fff',
        'on-secondary-container': '#ddd6fe',
        'tertiary': '#f183ff',
        'tertiary-dim': '#e050f0',
        'tertiary-fixed': '#f5a0ff',
        'tertiary-fixed-dim': '#f183ff',
        'tertiary-container': '#a019b0',
        'on-tertiary': '#000',
        'on-tertiary-fixed': '#000',
        'on-tertiary-fixed-variant': '#000',
        'on-tertiary-container': '#fce4ff',
        'error': '#ef4444',
        'error-dim': '#dc2626',
        'error-container': '#7f1d1d',
        'on-error': '#fff',
        'on-error-container': '#fecaca',
        'outline': '#262626',
        'outline-variant': '#1a1a1a',
        'surface-tint': '#3b82f6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'glow': '0 0 32px rgba(59, 130, 246, 0.15)',
        'glow-fuchsia': '0 8px 32px rgba(59, 130, 246, 0.08)',
        'neon': '0 0 20px rgba(59, 130, 246, 0.1)',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.1)' },
          '50%': { boxShadow: '0 0 40px rgba(59, 130, 246, 0.2)' },
        },
      },
    },
  },
  plugins: [],
};
