'use client';

import type { CSSProperties } from 'react';
import { useCallback, useEffect, useState } from 'react';
import type { EventFAQ, AutoFAQInput } from '../data/types';

const C = {
  bg: '#0A0A0A', surface: 'rgba(10, 10, 10, 0.86)', border: 'rgba(184, 180, 172, 0.18)',
  text: '#F5F5F0', textMuted: '#B8B4AC', accent: '#C8B89A', accentBg: 'rgba(200, 184, 154, 0.14)',
  error: '#fca5a5',
};

const card: CSSProperties = {
  background: C.surface, border: `1px solid ${C.border}`, borderRadius: 24,
  padding: 20, boxShadow: '0 20px 60px rgba(2, 6, 23, 0.28)',
};

const inp: CSSProperties = {
  width: '100%', borderRadius: 14, border: `1px solid ${C.border}`,
  background: 'rgba(10, 10, 10, 0.88)', color: C.text, padding: '10px 14px',
  fontSize: 14, outline: 'none', boxSizing: 'border-box',
};

const btnBase: CSSProperties = {
  border: 'none', borderRadius: 999, fontWeight: 700, cursor: 'pointer', padding: '10px 20px', fontSize: 13,
};

export default function AIFAQSection({ eventId, isHost, eventData }: {
  eventId: string;
  isHost?: boolean;
  eventData?: AutoFAQInput;
}) {
  const [faqs, setFaqs] = useState<EventFAQ[]>([]);
  const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading');
  const [showAdd, setShowAdd] = useState(false);
  const [newQ, setNewQ] = useState('');
  const [newA, setNewA] = useState('');

  const load = useCallback(async () => {
    setStatus('loading');
    try {
      const res = await fetch(`/api/event-os/faq/event/${eventId}`);
      if (!res.ok) throw new Error('Failed');
      setFaqs((await res.json()).faqs || []);
      setStatus('success');
    } catch { setStatus('error'); }
  }, [eventId]);

  useEffect(() => { load(); }, [load]);

  async function generate() {
    try {
      await fetch('/api/event-os/faq/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ eventId, ...eventData }),
      });
      load();
    } catch { /* ignore */ }
  }

  async function addManual() {
    if (!newQ.trim() || !newA.trim()) return;
    await fetch('/api/event-os/faq', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ eventId, question: newQ, answer: newA }),
    });
    setNewQ('');
    setNewA('');
    setShowAdd(false);
    load();
  }

  async function removeFaq(id: string) {
    await fetch(`/api/event-os/faq/${id}`, { method: 'DELETE' });
    load();
  }

  if (status === 'error') {
    return <div style={{ color: C.textMuted, fontSize: 13, padding: 12 }}>Could not load FAQ.</div>;
  }

  return (
    <div style={card}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
        <div style={{ fontWeight: 700, fontSize: 16 }}>FAQ</div>
        {isHost && (
          <div style={{ display: 'flex', gap: 6 }}>
            <button onClick={generate} style={{ ...btnBase, background: C.accentBg, color: C.accent, fontSize: 11 }}>Auto-generate</button>
            <button onClick={() => setShowAdd(!showAdd)} style={{ ...btnBase, background: C.accentBg, color: C.accent, fontSize: 11 }}>+ Add</button>
          </div>
        )}
      </div>

      {showAdd && (
        <div style={{ display: 'grid', gap: 8, padding: 12, marginBottom: 12, borderRadius: 16, background: 'rgba(15,23,42,0.6)' }}>
          <input value={newQ} onChange={e => setNewQ(e.target.value)} placeholder="Question" style={inp} />
          <input value={newA} onChange={e => setNewA(e.target.value)} placeholder="Answer" style={inp} />
          <button onClick={addManual} disabled={!newQ.trim() || !newA.trim()} style={{ ...btnBase, background: newQ.trim() && newA.trim() ? C.accent : C.border, color: '#fff' }}>Add FAQ</button>
        </div>
      )}

      {status === 'loading' ? (
        <p style={{ color: C.textMuted, fontSize: 13 }}>Loading...</p>
      ) : faqs.length === 0 ? (
        <p style={{ color: C.textMuted, fontSize: 13, margin: 0 }}>
          No FAQ yet. {isHost ? 'Click "Auto-generate" to create from event data.' : ''}
        </p>
      ) : (
        faqs.map(faq => (
          <div key={faq.id} style={{ padding: '10px 0', borderBottom: `1px solid ${C.border}` }}>
            <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 4 }}>{faq.question}</div>
            <div style={{ color: C.textMuted, fontSize: 13 }}>{faq.answer}</div>
            {faq.isAutoGenerated && <div style={{ fontSize: 10, color: C.accent, marginTop: 4 }}>Auto-generated</div>}
            {isHost && (
              <button onClick={() => removeFaq(faq.id)} style={{ background: 'none', border: 'none', color: C.error, cursor: 'pointer', fontSize: 11, padding: 0, marginTop: 4 }}>Remove</button>
            )}
          </div>
        ))
      )}
    </div>
  );
}
